name: Automatic Semantic Versioning

on:
  pull_request:
  push:
    branches:
      - main
      - prerelease

jobs:
  version:
    name: Automatic Semantic Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Bump Application Version and Tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          pre_release_branches: prerelease
          append_to_pre_release_tag: prerelease